#### M Jaswanth

# Numpy

### Numpy arrays and basic

In [1]:
import numpy as np

NumPy is a Python library used for numerical computing, especially handling multi-dimensional arrays efficiently. It also provides tools for linear algebra, statistics, and mathematical operations.

Example: In real life, if you’re analyzing sales data of a store across months and branches, NumPy arrays can store and process that data much faster than normal Python lists.

### creating array from list

In [2]:
arr_1d = np.array([1,2,3])
print(arr_1d)
type(arr_1d)

[1 2 3]


numpy.ndarray

In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
type(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

### list vs numpy array

A Python list can store different data types and is flexible but slower for numerical operations.

A NumPy array stores data of the same type in a contiguous block of memory, making it much faster and more memory-efficient for mathematical computations.

Example: If you want to calculate the total marks of 1,000 students, a NumPy array can sum them in one step, while a Python list would need a loop and take more time.

In [7]:
py_List = [1,2,3]
print(py_List)
print(py_List*2)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [10]:
py_list = [1,2,3]
print("Python list multiplication " , py_list * 2)
np_array = np.array( [1, 2, 3]) #element wise multiplication
print("python array multiplication",np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


In [12]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time: ", time.time() - start)
start = time.time()
np_array2 = np.arange(1000000)*2
print("\n Numpy Operation time: ", time.time() - start)


 List Operation time:  0.15500879287719727

 Numpy Operation time:  0.011174678802490234


### creating array from scratch

In [13]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [17]:
random = np.random.random((2,3))
print(random)

[[0.15104535 0.0443557  0.58028846]
 [0.12879131 0.51981162 0.27476108]]


In [7]:
np.random.randint(0, 10, size=(3, 3))

array([[2, 5, 4],
       [5, 4, 5],
       [0, 4, 2]])

In [4]:
sequence = np.arange(10)
print(sequence)
sequence = np.arange(0,10,2)
print(sequence)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


### vector, Matrix and Tensor

Vector → A 1-D array (like a list of numbers).
Example: A student’s marks in 5 subjects → [85, 90, 78, 92, 88].

Matrix → A 2-D array (rows × columns).
Example: Marks of 3 students in 5 subjects → a table with 3 rows and 5 columns.

Tensor → A multi-dimensional array (3-D or higher).
Example: A stack of matrices, like storing marks of students across multiple semesters.

In [20]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [21]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[6,7]]]) # multidimensional arrays
print(tensor)
print(tensor.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
3


### Array properties

In [24]:
arr = np.array([[1,2,3],[3,4,5]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("DataType",arr.dtype)

Shape (2, 3)
Dimension 2
size 6
DataType int32


### array reshaping

Array reshaping in NumPy means changing the shape/dimensions of an array without changing its data.

Common Methods:

reshape() – Changes shape to given dimensions.
Real life: Reshaping a flat list of 6 exam scores into a 2×3 table.

ravel() – Flattens array into 1-D (returns a view if possible).
Example: 2x3 → 1x6
Real life: Taking all marks from a table and lining them in a single row.

flatten() – Also flattens to 1-D but always returns a copy.
Example: Similar to ravel() but safer when you don’t want changes to affect the original.

resize() – Changes shape and size in-place. If needed, repeats data to fill.
Example: (3,) → (2,3) → fills extra spots by repeating elements.
Real life: Resizing attendance data to fit a fixed format sheet.

transpose() / .T – Swaps dimensions (rows ↔ columns).
Example: Student marks table → subjects vs students.

squeeze() – Removes dimensions of size 1.
Example: Shape (1,5,1) → (5,).
Real life: Removing unnecessary empty columns in data.

In [12]:
arr = np.arange(12)
print("Original array",arr)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
reshaped = arr.reshape((3,4))
print("\n Reshaped array",reshaped)


 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
flattened = reshaped.flatten()
print("\n flattened array", flattened)


 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [34]:
# ravel (returns view or original, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array", raveled)


 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
Transpose = reshaped.T
print("\n Transposed array", Transpose)


 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
squeeze = reshaped.squeeze();
print(squeeze)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Array Numpy Operations

#### slicing

Slicing in NumPy means extracting a part of the array using index ranges.
It follows the format:

array[start:end:step]

Examples:

1D Array

arr = np.array([10,20,30,40,50])

arr[1:4]   # [20,30,40]


👉 Like picking roll numbers 2 to 4 from a list.

2D Array (rows × columns)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr[0:2, 1:3]  # [[2,3],[5,6]]


👉 Like selecting marks of first 2 students but only in 2 subjects.

Step slicing

arr[::2]   # every 2nd element

In [37]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[2:7])
print("with step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic slicing [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [41]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire column",arr_2d[:,1])

Specific Element 6
Entire row [4 5 6]
Entire column [2 5 8]


#### sorting

Sorting in NumPy means arranging elements of an array in ascending (default) or descending order.

Methods:

np.sort(array) – Returns a sorted copy (doesn’t change original).

arr = np.array([30,10,20])

np.sort(arr)   # [10,20,30]


👉 Like sorting student marks from lowest to highest.

array.sort() – Sorts the array in-place (changes original).

Sorting 2D arrays

arr = np.array([[3,1,2],[9,7,8]])

np.sort(arr, axis=1)  # sort each row

np.sort(arr, axis=0)  # sort each column


👉 Example: Sorting marks of each student individually (row-wise) vs. sorting subject-wise across students (column-wise).

np.argsort(array) – Returns indices that would sort the array.
👉 Example: Getting student roll numbers in order of their marks.

In [ ]:
unsorted = np.array([1,4,2,6,5,2])
print("sorted array",np.sort(unsorted))

sorted array [1 2 2 4 5 6]


In [12]:
unsorted_2d = np.array([[4,3,9],[8,7,6]])
print("Sorted 2D array", np.sort(unsorted_2d,axis = 0))
print("Sorted 2D array", np.sort(unsorted_2d,axis = 1))

Sorted 2D array [[4 3 6]
 [8 7 9]]
Sorted 2D array [[3 4 9]
 [6 7 8]]


In [10]:
unsorted_2d = np.array([[3,7,5],[8,3,2]])
print("Sorted 2D array", np.sort(unsorted_2d,axis = 0))
print("Sorted 2D array", np.sort(unsorted_2d,axis = 1))

Sorted 2D array [[3 3 2]
 [8 7 5]]
Sorted 2D array [[3 5 7]
 [2 3 8]]


In [49]:
unsorted_2d = np.array([[3,1],[3,2],[2,1]])
print("Sorted 2D array", np.sort(unsorted_2d,axis = 0))

Sorted 2D array [[2 1]
 [3 1]
 [3 2]]


#### Filter

Filtering in NumPy means selecting elements from an array based on a condition (Boolean indexing).

Example:
arr = np.array([10, 20, 30, 40, 50])
filter = arr > 25
result = arr[filter]   # [30, 40, 50]


👉 Like filtering students who scored more than 25 marks.

🔹 Does it change the original array?
No ❌, filtering creates a new array. The original stays unchanged unless you explicitly reassign it.

In [21]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print("Even numbers",even_number)

Even numbers [ 2  4  6  8 10]


#### Filter with mask

In [65]:
mask = numbers>5
print(mask)
print("Numbers greater than 5",numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers greater than 5 [ 6  7  8  9 10]


#### Fancy indexing vs np.where()

In [61]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


np.where is used to return indices where a condition is true, or to apply a condition and return values accordingly.

1. Get Indices
arr = np.array([10,20,30,40])

np.where(arr > 25)   # (array([2, 3]),)


👉 Tells positions of students scoring above 25.

2. Conditional Selection

np.where(arr > 25, "Pass", "Fail") # ['Fail','Fail','Pass','Pass']


👉 Replaces values based on condition (like marking Pass/Fail).

📌 When to use?

To find positions of elements meeting a condition.

To replace/label data based on a condition.

In [22]:
where_result  = np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])

(array([5, 6, 7, 8, 9], dtype=int64),)
NP where [ 6  7  8  9 10]


np.where(condition, if true what to perform, else what to perform)

In [70]:
condition_array = np.where(numbers>5,"true","false") 
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
condition_array = np.where(numbers>5,numbers*2,numbers) # where creates array with specific conditions
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


#### Adding and removing data

In [71]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
combined = np.concatenate((arr1,arr2))
print(combined)

[ 1  2  3  4  5  6  7  8  9 10]


#### array compatibility

In [73]:
a = np.array([1,2,3])
b = np.array([4,5,6,0])
c = np.array([7,8,9])
print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [31]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [32]:
new_col = np.array([[7],[8]])
with_new_column = np.hstack((original,new_col))
print(with_new_column)

[[1 2 7]
 [3 4 8]]


#### delete

In [81]:
arr = np.array([1,2,3,4])
deleted= np.delete(arr,2)
print(deleted)

[1 2 4]


np.random.rand() → Generates numbers from a uniform distribution between 0 and 1.
Example: np.random.rand(3) → [0.23, 0.77, 0.54]

np.random.randn() → Generates numbers from a standard normal distribution (mean 0, std 1).
Example: np.random.randn(3) → [0.45, -1.23, 0.67]

Real life:

rand() → Like rolling a fair dice and dividing by 6.

randn() → Like measuring heights of people, which cluster around average.

Uniform Distribution → Every value in a given range has an equal probability of occurring.
👉 Example: Rolling a fair dice (1–6 all equally likely).

Normal Distribution → Data is distributed in a bell curve: most values are around the mean, and fewer values occur at extremes.
👉 Example: Students’ exam scores usually cluster around the average, with very few scoring extremely low or high.

📌 In NumPy,

np.random.uniform(low, high, size) → generates uniform distribution.

np.random.normal(mean, std, size) → generates normal distribution.

In [33]:
np.random.rand(3, 3)  # Uniform distribution

array([[0.88434169, 0.62685467, 0.3049596 ],
       [0.04558504, 0.0228787 , 0.33171746],
       [0.83349105, 0.9235345 , 0.21307882]])

In [5]:
np.random.randn(3, 3) # Normal distribution

array([[-0.11929595, -0.08069572, -1.55521425],
       [-0.40680632, -0.65318041, -1.35482259],
       [ 0.13034221,  0.57204575,  2.07937193]])